# @baseURL=https://ibeaconattendanceproject-api.onrender.com
@baseURL=https://ibeacon-api.cyclic.app
# @baseURL=http://localhost:8080
@accessTokenInstructor=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJiYzk5OWI2NmU1MDhmYmRlMDAxMWYiLCJuYW1lIjoiSmFsYWwgRmFvdXIiLCJlbWFpbCI6ImFobWFkamFsYWxmYW91ckBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRGcklKR25JNWo4N3B0Qk9VM2lTdThPaHFaTnozSnluOUIwTFdMcEJleTBWNGIuUERVSTl3cSIsInJvbGUiOiJpbnN0cnVjdG9yIiwidW5pcXVlSWQiOiI4ZGVhZWU0MGZmY2Y2NzQ0IiwiZmNtVG9rZW4iOiJjSU5EdUgtSFFmLWVLN0N4Qy1aWFB5OkFQQTkxYkV2cm4tREtGUzVvSFE3anhfcWE2VFloSS1TdThwNnFqUzNGNFRuanlmc0NkaEZ2WlR5d2syNGVoWklzTlhhbVBPNjVVWkJMQmhNdFN3d0RBdWFyQThqMURUZk9UejI3TFRzaFd3dTdnTHg1Njk4S0xWQWxhd1hIV3N0OVFiRDUwdnZGYU9LIiwidW5pdmVyc2l0eU5hbWUiOiJiZWFjb24iLCJzdGF0dXMiOiJhY3RpdmF0ZWQiLCJfX3YiOjAsImlhdCI6MTcwNjgwNTg0NCwiZXhwIjoxNzA3NDEwNjQ0fQ.O3sP5quMAu7Q68QLWAtjOwFM8c251yg8ovbamrV6__4
@accessTokenStudent=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWI1MzJmNzQ3M2JjYmRhY2QxNjA3NDEiLCJuYW1lIjoiSmFsYWwiLCJlbWFpbCI6ImFobWFkZmFvdXI4QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEVmZ2hzaDFPOVBoUXQwOHhJL2o1VS5rRGIwVmhrZnFMWVZDbUFaMDlNSWYwTEE4TFdlM1NLIiwicm9sZSI6InN0dWRlbnQiLCJjb2xsZWdlSWQiOjI4ODgsInVuaXF1ZUlkIjoiOGRlYWVlNDBmZmNmNjc0NCIsImZjbVRva2VuIjoiZmhXbnY5dHVTSUc5NFl0ZkRjTDUyTTpBUEE5MWJIVklSREh0bG0zYnd6cGx0cC1EY3lXYUV4TmRCR25FbWNBclI4dk5pb2dnOTNJb3d6b01uNEZrekE5enc5YjRkRnRUZjlXY1dpYmZzOS1hSEloN0hZM0xwU2ZjTkpfaENqUkN5V0V0N2xBb3U3ZFMtb3RNQUcxaU1hQkIwWGZEdEczclIzSSIsInVuaXZlcnNpdHlOYW1lIjoiU3lyaWEiLCJzdGF0dXMiOiJhY3RpdmF0ZWQiLCJfX3YiOjAsImlhdCI6MTcwNjM3NTY4MiwiZXhwIjoxNzA2OTgwNDgyfQ.4jaEgMlVJvlnoUghGeejiSoGg4m9D6ne7OxYWJjRssc

###

GET {{baseURL}}/ 

### signup as insturctor

POST {{baseURL}}/signup 
Content-Type: application/json

{
    "name":"in1",
    "email":"ilovepython90@gmail.com",
    "password":"ali",
    "universityName":"test",
    "role":"instructor"
}

### signup as student

POST {{baseURL}}/signup 
Content-Type: application/json

{
    "name":"ahmadjalalfaour",
    "email":"ahmadjalalfaour@gmail.com",
    "password":"jalal",
    "universityName":"test",
    "role":"student",
    "collegeId": 55121
}

### login

POST {{baseURL}}/login 
Content-Type: application/json

{
    "email":"ahmadjalalfaour@gmail.com",
    "password":"jalal",
    "uniqueId": "8deaee40ffcf6744"
}

### activate account

POST {{baseURL}}/activateAccount
Content-Type: application/json

{
    "key": "819055"
}

### Get all courses

GET {{baseURL}}/course
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

### Get a course

GET {{baseURL}}/course/65a191b973cc48364c6ef917
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

### Add course

POST {{baseURL}}/course 
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

{
    "name": "New Course 5",
    "room": "lab 5",
    "hoursOfDeprivation": 5
}

### Edit course details

PUT {{baseURL}}/course/65a191b973cc48364c6ef917
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

{
    "name": "New Course 1",
    "room": "lab 1"
}

### Get all appointments of a course

GET {{baseURL}}/course/65ae9da93d79622b9cf53aa7/appointment
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

### Get appointment details

GET {{baseURL}}/course/65a8175449dd3d6957d186a8/appointment/659ef1e0358e8c6b18a4ac2f
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}


### Add new appointment to a course

POST {{baseURL}}/course/65ae9da93d79622b9cf53aa7/appointment
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

{
    "name": "t session",
    "start": "2024-01-21T23:38:25.891+00:00",
    "end": "2024-01-21T23:38:25.891+00:00"
}

### Edit an appointment

PUT {{baseURL}}/course/65a191b973cc48364c6ef917/appointment/659effaf22f393e6e79580ad
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

{
    "name": "Third Session",
    "start": "Wed, 10 Jan 2024 19:36:32 GMT",
    "end": "Wed, 11 Jan 2024 21:36:32 GMT"
}


### Get students in course

GET {{baseURL}}/course/65a8175449dd3d6957d186a8/students
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}


### Add (list) of students to a course

POST {{baseURL}}/course/65bbc9e9b66e508fbde0012a/addStudentsByArray
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

{
    "studentsIds": ["65bbcad828dcabbd9338db07"]
}


### Add (list) of students to a course by excel

POST {{baseURL}}/course/65a8175449dd3d6957d186a8/addStudentsByArray
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

{
    "excel": 
}


### check appointment status

GET {{baseURL}}/appointment/65a817d649dd3d6957d186bc/isOpen
Content-Type: application/json
Authorization: Bearer {{accessTokenStudent}}

### Attend a student to an appointment

POST {{baseURL}}/appointment/65a817c549dd3d6957d186b9/attend
Content-Type: application/json
Authorization: Bearer {{accessTokenStudent}}

### Attend a student by id manualy by instructor

POST {{baseURL}}/appointment/65a817c549dd3d6957d186b9/attendStudentById
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

{
    "studentId": "65a8162949dd3d6957d186a4"
}

### Get students status for abscence and attendance

GET {{baseURL}}/appointment/65a817c549dd3d6957d186b9/students
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

### Get absence to for appointment

GET {{baseURL}}/apology
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}


### Add absence to an appointment

POST {{baseURL}}/appointment/65a817c549dd3d6957d186b9/apology
Content-Type: application/json
Authorization: Bearer {{accessTokenStudent}}

{
    "reason": "test"
}

### Send Notifications
POST {{baseURL}}/course/65aeb2d49c1a32492fcf859b/sendNotification
Content-Type: application/json
Authorization: Bearer {{accessTokenInstructor}}

{
    "title": "اول اشعار",
    "description": "اول اشعار"
}

### get Notifications for a student

GET {{baseURL}}/notification
Content-Type: application/json
Authorization: Bearer {{accessTokenStudent}}

